{% set name = "napari-live-recording" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c08ca857ca4b57a9ac1ff6d66a01b78dbaac50ea3ef3a38c375bba9f56d0ae0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - setuptools-scm
  run:
    # - h5py  # Listed but unused
    - microscope
    - napari
    - numpy
    # - np-image-buffer  # Listed but unused
    - opencv
    - pymmcore-plus >=0.6.7
    - pymmcore-widgets
    - python >=3.6,<3.10
    - qtpy
    - superqt
    - tifffile

test:
  imports:
    - napari_live_recording
  commands:
    - pip list
    # - pip check  # Fails due to opencv-contrib and listed but unused dependencies
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-live-recording
  summary: A napari plugin for live video recording with a generic camera device.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/jacopoabramo/napari-live-recording

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jacopoabramo
