{% set name = "napari-live-recording" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_live_recording-{{ version }}.tar.gz
  sha256: 6b02288ebf6f136f552611472795ecece572af8853ae08bac8e68c0a81966066

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - setuptools-scm
  run:
    - dask-image
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - opencv
    - qtpy
    - superqt
    - python >=3.6,<3.10

test:
  imports:
    - napari_live_recording
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/jethro33/napari-live-recording
  summary: A napari plugin for live video recording with a generic camera device.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jacopoabramo
