{% set name = "napari-live-recording" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 13558f3ffc80608b669b624e0dcd53a62b0ab8e60c8a0da6c9695f6539cdb6ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.10
    - setuptools-scm
  run:
    - dask-image
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - opencv
    - qtpy
    - superqt
    - python >=3.6,<3.10

test:
  imports:
    - napari_live_recording
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/jethro33/napari-live-recording
  summary: A napari plugin for live video recording with a generic camera device.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jacopoabramo
